server:
  port: 8080
  servlet:
    context-path: /kwedu

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: roywmc83
    protocol: smtp
    default-encoding: UTF-8
    password: euqjcuvfzogygvtz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
service:
  email:
    default-subject: title
    send-to-list:
      - lyjoon@gmail.com
      - roywmc83@gmail.com
    send-from: lyjoon@gmail.com