server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lyjoon@gmail.com
    protocol: smtp
    default-encoding: UTF-8
    password: cjhtjmrurgfbdlft
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
service:
  email:
    default-subject: title
    send-to-list:
      - lyjoon@gmail.com
      - roywmc83@gmail.com
      - jiaebb@nate.com
      - i_am_bin@hanmail.net
    send-from: lyjoon@gmail.com