server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: roywmc83
    password: 2dydwns2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
service:
  email:
    default-subject: title
    send-to-list:
      - lyjoon@gmail.com
      - roywmc83@gmail.com
    send-from: roywmc83@gmail.com